(cl:in-package dji_sdk-msg)
(cl:export '(MISSIONINDEX-VAL
          MISSIONINDEX
          LATLNTCOUNT-VAL
          LATLNTCOUNT
          LATLNTLIST-VAL
          LATLNTLIST
          ACTIONCOUNT-VAL
          ACTIONCOUNT
          WAYPOINTACTION-VAL
          WAYPOINTACTION
          ALTITUDE-VAL
          ALTITUDE
          VELOCITY-VAL
          VELOCITY
          FINISHACTION-VAL
          FINISHACTION
          HEADINGMODE-VAL
          HEADINGMODE
          GIMBALANGLE-VAL
          GIMBALANGLE
          REPEATTIMES-VAL
          REPEATTIMES
          ISUSECAM-VAL
          ISUSECAM
          SOR-VAL
          SOR
          SHOOTVEL-VAL
          SHOOTVEL
))