# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_sdk/Emergency.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Emergency(genpy.Message):
  _md5sum = "1d411b8cc595547a01bef8995efbdc30"
  _type = "dji_sdk/Emergency"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/UInt8 home
std_msgs/UInt8 land
std_msgs/UInt8 hover
std_msgs/UInt8 takeOff

================================================================================
MSG: std_msgs/UInt8
uint8 data
"""
  __slots__ = ['home','land','hover','takeOff']
  _slot_types = ['std_msgs/UInt8','std_msgs/UInt8','std_msgs/UInt8','std_msgs/UInt8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       home,land,hover,takeOff

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Emergency, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.home is None:
        self.home = std_msgs.msg.UInt8()
      if self.land is None:
        self.land = std_msgs.msg.UInt8()
      if self.hover is None:
        self.hover = std_msgs.msg.UInt8()
      if self.takeOff is None:
        self.takeOff = std_msgs.msg.UInt8()
    else:
      self.home = std_msgs.msg.UInt8()
      self.land = std_msgs.msg.UInt8()
      self.hover = std_msgs.msg.UInt8()
      self.takeOff = std_msgs.msg.UInt8()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.home.data, _x.land.data, _x.hover.data, _x.takeOff.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.home is None:
        self.home = std_msgs.msg.UInt8()
      if self.land is None:
        self.land = std_msgs.msg.UInt8()
      if self.hover is None:
        self.hover = std_msgs.msg.UInt8()
      if self.takeOff is None:
        self.takeOff = std_msgs.msg.UInt8()
      end = 0
      _x = self
      start = end
      end += 4
      (_x.home.data, _x.land.data, _x.hover.data, _x.takeOff.data,) = _get_struct_4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.home.data, _x.land.data, _x.hover.data, _x.takeOff.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.home is None:
        self.home = std_msgs.msg.UInt8()
      if self.land is None:
        self.land = std_msgs.msg.UInt8()
      if self.hover is None:
        self.hover = std_msgs.msg.UInt8()
      if self.takeOff is None:
        self.takeOff = std_msgs.msg.UInt8()
      end = 0
      _x = self
      start = end
      end += 4
      (_x.home.data, _x.land.data, _x.hover.data, _x.takeOff.data,) = _get_struct_4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
