# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_sdk/GimCtr.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class GimCtr(genpy.Message):
  _md5sum = "884bd8fe246ac26d7bb87013a1d884c1"
  _type = "dji_sdk/GimCtr"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point pry
std_msgs/Int32 mutiple
std_msgs/Int32 setFcus
std_msgs/Int32 reset
std_msgs/Int32 sos
std_msgs/Int32 sor
		


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: std_msgs/Int32
int32 data"""
  __slots__ = ['pry','mutiple','setFcus','reset','sos','sor']
  _slot_types = ['geometry_msgs/Point','std_msgs/Int32','std_msgs/Int32','std_msgs/Int32','std_msgs/Int32','std_msgs/Int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pry,mutiple,setFcus,reset,sos,sor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GimCtr, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pry is None:
        self.pry = geometry_msgs.msg.Point()
      if self.mutiple is None:
        self.mutiple = std_msgs.msg.Int32()
      if self.setFcus is None:
        self.setFcus = std_msgs.msg.Int32()
      if self.reset is None:
        self.reset = std_msgs.msg.Int32()
      if self.sos is None:
        self.sos = std_msgs.msg.Int32()
      if self.sor is None:
        self.sor = std_msgs.msg.Int32()
    else:
      self.pry = geometry_msgs.msg.Point()
      self.mutiple = std_msgs.msg.Int32()
      self.setFcus = std_msgs.msg.Int32()
      self.reset = std_msgs.msg.Int32()
      self.sos = std_msgs.msg.Int32()
      self.sor = std_msgs.msg.Int32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d5i().pack(_x.pry.x, _x.pry.y, _x.pry.z, _x.mutiple.data, _x.setFcus.data, _x.reset.data, _x.sos.data, _x.sor.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pry is None:
        self.pry = geometry_msgs.msg.Point()
      if self.mutiple is None:
        self.mutiple = std_msgs.msg.Int32()
      if self.setFcus is None:
        self.setFcus = std_msgs.msg.Int32()
      if self.reset is None:
        self.reset = std_msgs.msg.Int32()
      if self.sos is None:
        self.sos = std_msgs.msg.Int32()
      if self.sor is None:
        self.sor = std_msgs.msg.Int32()
      end = 0
      _x = self
      start = end
      end += 44
      (_x.pry.x, _x.pry.y, _x.pry.z, _x.mutiple.data, _x.setFcus.data, _x.reset.data, _x.sos.data, _x.sor.data,) = _get_struct_3d5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d5i().pack(_x.pry.x, _x.pry.y, _x.pry.z, _x.mutiple.data, _x.setFcus.data, _x.reset.data, _x.sos.data, _x.sor.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pry is None:
        self.pry = geometry_msgs.msg.Point()
      if self.mutiple is None:
        self.mutiple = std_msgs.msg.Int32()
      if self.setFcus is None:
        self.setFcus = std_msgs.msg.Int32()
      if self.reset is None:
        self.reset = std_msgs.msg.Int32()
      if self.sos is None:
        self.sos = std_msgs.msg.Int32()
      if self.sor is None:
        self.sor = std_msgs.msg.Int32()
      end = 0
      _x = self
      start = end
      end += 44
      (_x.pry.x, _x.pry.y, _x.pry.z, _x.mutiple.data, _x.setFcus.data, _x.reset.data, _x.sos.data, _x.sor.data,) = _get_struct_3d5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d5i = None
def _get_struct_3d5i():
    global _struct_3d5i
    if _struct_3d5i is None:
        _struct_3d5i = struct.Struct("<3d5i")
    return _struct_3d5i
