# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roblink_driver/GimbalCtl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GimbalCtl(genpy.Message):
  _md5sum = "3da712e93e361ce644847f1c37d59c65"
  _type = "roblink_driver/GimbalCtl"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 pitch
float32 yaw
float32 zoom
float32 focus
uint16  home
uint16  TakePicture
uint16  cameraModeChange
uint16  yawfollow
"""
  __slots__ = ['pitch','yaw','zoom','focus','home','TakePicture','cameraModeChange','yawfollow']
  _slot_types = ['float32','float32','float32','float32','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pitch,yaw,zoom,focus,home,TakePicture,cameraModeChange,yawfollow

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GimbalCtl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.zoom is None:
        self.zoom = 0.
      if self.focus is None:
        self.focus = 0.
      if self.home is None:
        self.home = 0
      if self.TakePicture is None:
        self.TakePicture = 0
      if self.cameraModeChange is None:
        self.cameraModeChange = 0
      if self.yawfollow is None:
        self.yawfollow = 0
    else:
      self.pitch = 0.
      self.yaw = 0.
      self.zoom = 0.
      self.focus = 0.
      self.home = 0
      self.TakePicture = 0
      self.cameraModeChange = 0
      self.yawfollow = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f4H().pack(_x.pitch, _x.yaw, _x.zoom, _x.focus, _x.home, _x.TakePicture, _x.cameraModeChange, _x.yawfollow))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.pitch, _x.yaw, _x.zoom, _x.focus, _x.home, _x.TakePicture, _x.cameraModeChange, _x.yawfollow,) = _get_struct_4f4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f4H().pack(_x.pitch, _x.yaw, _x.zoom, _x.focus, _x.home, _x.TakePicture, _x.cameraModeChange, _x.yawfollow))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.pitch, _x.yaw, _x.zoom, _x.focus, _x.home, _x.TakePicture, _x.cameraModeChange, _x.yawfollow,) = _get_struct_4f4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f4H = None
def _get_struct_4f4H():
    global _struct_4f4H
    if _struct_4f4H is None:
        _struct_4f4H = struct.Struct("<4f4H")
    return _struct_4f4H
