// Generated by gencpp from file dji_sdk/HotpointMission.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_HOTPOINTMISSION_H
#define DJI_SDK_MESSAGE_HOTPOINTMISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/UInt8.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/Int16.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>

namespace dji_sdk
{
template <class ContainerAllocator>
struct HotpointMission_
{
  typedef HotpointMission_<ContainerAllocator> Type;

  HotpointMission_()
    : missionIndex()
    , hotpoint()
    , startHotPoint()
    , headingMode()
    , altitude()
    , angleVel()
    , radius()
    , gimbalAngle()
    , clockwise()
    , isUseCam()
    , sor()
    , shootVel()  {
    }
  HotpointMission_(const ContainerAllocator& _alloc)
    : missionIndex(_alloc)
    , hotpoint(_alloc)
    , startHotPoint(_alloc)
    , headingMode(_alloc)
    , altitude(_alloc)
    , angleVel(_alloc)
    , radius(_alloc)
    , gimbalAngle(_alloc)
    , clockwise(_alloc)
    , isUseCam(_alloc)
    , sor(_alloc)
    , shootVel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _missionIndex_type;
  _missionIndex_type missionIndex;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _hotpoint_type;
  _hotpoint_type hotpoint;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _startHotPoint_type;
  _startHotPoint_type startHotPoint;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _headingMode_type;
  _headingMode_type headingMode;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _altitude_type;
  _altitude_type altitude;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _angleVel_type;
  _angleVel_type angleVel;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _radius_type;
  _radius_type radius;

   typedef  ::std_msgs::Int16_<ContainerAllocator>  _gimbalAngle_type;
  _gimbalAngle_type gimbalAngle;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _clockwise_type;
  _clockwise_type clockwise;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _isUseCam_type;
  _isUseCam_type isUseCam;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _sor_type;
  _sor_type sor;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _shootVel_type;
  _shootVel_type shootVel;





  typedef boost::shared_ptr< ::dji_sdk::HotpointMission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_sdk::HotpointMission_<ContainerAllocator> const> ConstPtr;

}; // struct HotpointMission_

typedef ::dji_sdk::HotpointMission_<std::allocator<void> > HotpointMission;

typedef boost::shared_ptr< ::dji_sdk::HotpointMission > HotpointMissionPtr;
typedef boost::shared_ptr< ::dji_sdk::HotpointMission const> HotpointMissionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_sdk::HotpointMission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_sdk::HotpointMission_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_sdk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'dji_sdk': ['/home/dji/DJI_Onboard_Sdk/src/Onboard-SDK-ROS/dji_sdk/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_sdk::HotpointMission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_sdk::HotpointMission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_sdk::HotpointMission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_sdk::HotpointMission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_sdk::HotpointMission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_sdk::HotpointMission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_sdk::HotpointMission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1275f1566cde5c929e0caa2875c0e3c4";
  }

  static const char* value(const ::dji_sdk::HotpointMission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1275f1566cde5c92ULL;
  static const uint64_t static_value2 = 0x9e0caa2875c0e3c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_sdk::HotpointMission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_sdk/HotpointMission";
  }

  static const char* value(const ::dji_sdk::HotpointMission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_sdk::HotpointMission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/UInt8 missionIndex\n\
geometry_msgs/Point hotpoint\n\
std_msgs/UInt8 startHotPoint\n\
std_msgs/UInt8 headingMode\n\
std_msgs/UInt16 altitude\n\
std_msgs/UInt8 angleVel\n\
std_msgs/UInt16 radius\n\
std_msgs/Int16 gimbalAngle\n\
std_msgs/UInt8 clockwise\n\
std_msgs/UInt8 isUseCam\n\
std_msgs/UInt8 sor\n\
std_msgs/UInt8 shootVel\n\
\n\
================================================================================\n\
MSG: std_msgs/UInt8\n\
uint8 data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: std_msgs/UInt16\n\
uint16 data\n\
\n\
================================================================================\n\
MSG: std_msgs/Int16\n\
int16 data\n\
";
  }

  static const char* value(const ::dji_sdk::HotpointMission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_sdk::HotpointMission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.missionIndex);
      stream.next(m.hotpoint);
      stream.next(m.startHotPoint);
      stream.next(m.headingMode);
      stream.next(m.altitude);
      stream.next(m.angleVel);
      stream.next(m.radius);
      stream.next(m.gimbalAngle);
      stream.next(m.clockwise);
      stream.next(m.isUseCam);
      stream.next(m.sor);
      stream.next(m.shootVel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HotpointMission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_sdk::HotpointMission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_sdk::HotpointMission_<ContainerAllocator>& v)
  {
    s << indent << "missionIndex: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.missionIndex);
    s << indent << "hotpoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.hotpoint);
    s << indent << "startHotPoint: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.startHotPoint);
    s << indent << "headingMode: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.headingMode);
    s << indent << "altitude: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.altitude);
    s << indent << "angleVel: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.angleVel);
    s << indent << "radius: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.radius);
    s << indent << "gimbalAngle: ";
    s << std::endl;
    Printer< ::std_msgs::Int16_<ContainerAllocator> >::stream(s, indent + "  ", v.gimbalAngle);
    s << indent << "clockwise: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.clockwise);
    s << indent << "isUseCam: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.isUseCam);
    s << indent << "sor: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.sor);
    s << indent << "shootVel: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.shootVel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_SDK_MESSAGE_HOTPOINTMISSION_H
